//
//  Record.swift
//  oye baryani
//
//  Created by Apple on 21/01/2020.
//  Copyright © 2020 Apple. All rights reserved.
//

import Foundation

class Record{
    
    
    var id : String!
    var name : String!
    var image : String!
    var flavour : String!
    var price : String!
    var cat_id:String!
    var product_description : String!
    var image_1 : String!
    var image_2 : String!
    var image_3 : String!
    var size : String!
    var side_order : String!
    var idd : String!
    var imagee : String!
    var text : String!
    var value : String!
    
}






//{
//    "error": false,
//    "error_msg": "Showing All Products",
//    "records": [
//        {
//            "id": "271",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1582552667446",
//            "date_time": "2020-02-24 08:57:48",
//            "total_price": "439",
//            "status": "5",
//            "address": "House No. 45, Street 35, model town",
//            "gps_address": "67, Block C1 Block C 1 Phase 1 Model Town, Lahore, Punjab 54600, Pakistan",
//            "location": "31.4533084,74.291984",
//            "sec_mobile": "03445774617",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "3",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "266",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1582550328717",
//            "date_time": "2020-02-24 08:18:49",
//            "total_price": "439",
//            "status": "6",
//            "address": "House No. 45, Street 35, model town",
//            "gps_address": "67, Block C1 Block C 1 Phase 1 Model Town, Lahore, Punjab 54600, Pakistan",
//            "location": "31.4533084,74.291984",
//            "sec_mobile": "03445774617",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "3",
//            "status_name": "Canceled by user"
//        },
//        {
//            "id": "265",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1582550208054",
//            "date_time": "2020-02-24 08:16:49",
//            "total_price": "315",
//            "status": "6",
//            "address": "House No. 45, Street 35, model town",
//            "gps_address": "67, Block C1 Block C 1 Phase 1 Model Town, Lahore, Punjab 54600, Pakistan",
//            "location": "31.4533084,74.291984",
//            "sec_mobile": "03445774617",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "3",
//            "status_name": "Canceled by user"
//        },
//        {
//            "id": "263",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1582550104375",
//            "date_time": "2020-02-24 08:15:07",
//            "total_price": "265",
//            "status": "6",
//            "address": "House No. 45, Street 35, model town",
//            "gps_address": "67, Block C1 Block C 1 Phase 1 Model Town, Lahore, Punjab 54600, Pakistan",
//            "location": "31.4533084,74.291984",
//            "sec_mobile": "03445774617",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by user"
//        },
//        {
//            "id": "262",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1582550081704",
//            "date_time": "2020-02-24 08:14:44",
//            "total_price": "265",
//            "status": "5",
//            "address": "House No. 45, Street 35, model town",
//            "gps_address": "67, Block C1 Block C 1 Phase 1 Model Town, Lahore, Punjab 54600, Pakistan",
//            "location": "31.4533084,74.291984",
//            "sec_mobile": "03445774617",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "261",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1582550078351",
//            "date_time": "2020-02-24 08:14:43",
//            "total_price": "265",
//            "status": "5",
//            "address": "House No. 45, Street 35, model town",
//            "gps_address": "67, Block C1 Block C 1 Phase 1 Model Town, Lahore, Punjab 54600, Pakistan",
//            "location": "31.4533084,74.291984",
//            "sec_mobile": "03445774617",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "2",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "219",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1582394731498",
//            "date_time": "2020-02-22 13:05:33",
//            "total_price": "276",
//            "status": "5",
//            "address": "House No. 45, Street 35, model town",
//            "gps_address": "67, Block C1 Block C 1 Phase 1 Model Town, Lahore, Punjab 54600, Pakistan",
//            "location": "31.4533084,74.291984",
//            "sec_mobile": "03095927355",
//            "r_id": "1",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "15",
//            "branch_email": "",
//            "count": "3",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "36",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581891839881",
//            "date_time": "2020-02-16 17:24:00",
//            "total_price": "625",
//            "status": "5",
//            "address": "House No. 56,Street 45",
//            "gps_address": "Barelvi Rd, Pak Colony, SITE, Karachi, Sindh, Pak Colony Karachi, Karachi City, Sindh, Pakistan",
//            "location": "24.9021777,67.0210327",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "Not yet",
//            "accepted_by": "None",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "4",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "35",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581891489171",
//            "date_time": "2020-02-16 17:18:09",
//            "total_price": "125",
//            "status": "6",
//            "address": "House No. 56,Street 45",
//            "gps_address": "Barelvi Rd, Pak Colony, SITE, Karachi, Sindh, Pak Colony Karachi, Karachi City, Sindh, Pakistan",
//            "location": "24.9021777,67.0210327",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "Wow",
//            "accepted_by": "None",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "3",
//            "status_name": "Canceled by user"
//        },
//        {
//            "id": "34",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581891378338",
//            "date_time": "2020-02-16 17:16:20",
//            "total_price": "375",
//            "status": "6",
//            "address": "House No. 56,Street 45",
//            "gps_address": "Barelvi Rd, Pak Colony, SITE, Karachi, Sindh, Pak Colony Karachi, Karachi City, Sindh, Pakistan",
//            "location": "24.9021777,67.0210327",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "Wow",
//            "accepted_by": "None",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by user"
//        },
//        {
//            "id": "33",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581891344416",
//            "date_time": "2020-02-16 17:15:45",
//            "total_price": "375",
//            "status": "5",
//            "address": "House No. 56,Street 45",
//            "gps_address": "Barelvi Rd, Pak Colony, SITE, Karachi, Sindh, Pak Colony Karachi, Karachi City, Sindh, Pakistan",
//            "location": "24.9021777,67.0210327",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "Wow",
//            "accepted_by": "None",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "2",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "32",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581891247519",
//            "date_time": "2020-02-16 17:14:08",
//            "total_price": "196",
//            "status": "6",
//            "address": "House No. 56,Street 45",
//            "gps_address": "Barelvi Rd, Pak Colony, SITE, Karachi, Sindh, Pak Colony Karachi, Karachi City, Sindh, Pakistan",
//            "location": "24.9021777,67.0210327",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "Wow",
//            "accepted_by": "None",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "3",
//            "status_name": "Canceled by user"
//        },
//        {
//            "id": "12",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581011904012",
//            "date_time": "2020-02-06 12:58:26",
//            "total_price": "625",
//            "status": "5",
//            "address": "House 2, Street 2, Islamabad",
//            "gps_address": "1050, Street 02, Islamabad",
//            "location": "0",
//            "sec_mobile": "03095927355",
//            "r_id": "123",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "4",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "11",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581010552178",
//            "date_time": "2020-02-06 12:35:54",
//            "total_price": "575",
//            "status": "4",
//            "address": "House 2, Street 2, Islamabad",
//            "gps_address": "1050, Street 02, Islamabad",
//            "location": "0",
//            "sec_mobile": "03095927355",
//            "r_id": "202",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by rider"
//        },
//        {
//            "id": "10",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581002799200",
//            "date_time": "2020-02-06 10:26:40",
//            "total_price": "625",
//            "status": "5",
//            "address": "House 1, Street 1, Rawalpindi",
//            "gps_address": "1047, Street 01, Rawalpindi",
//            "location": "0",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "Oky",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "9",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581002671591",
//            "date_time": "2020-02-06 10:24:32",
//            "total_price": "775",
//            "status": "5",
//            "address": "House 1, Street 1, Rawalpindi",
//            "gps_address": "1047, Street 01, Rawalpindi",
//            "location": "0",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "8",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581001238914",
//            "date_time": "2020-02-06 10:00:40",
//            "total_price": "250",
//            "status": "5",
//            "address": "House 2, Street 2, Islamabad",
//            "gps_address": "1050, Street 02, Islamabad",
//            "location": "0",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "7",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1581001105238",
//            "date_time": "2020-02-06 09:58:28",
//            "total_price": "625",
//            "status": "5",
//            "address": "House No. 5,Street No. 10",
//            "gps_address": "Plot 613, Umer Block Umar Block Allama Iqbal Town, Lahore, Punjab, Pakistan",
//            "location": "31.5085393,74.280752",
//            "sec_mobile": "03095927355",
//            "r_id": "0",
//            "description": "",
//            "accepted_by": "None",
//            "coupen_off": "0",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "6",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1580982292931",
//            "date_time": "2020-02-06 04:44:54",
//            "total_price": "1125",
//            "status": "5",
//            "address": "House 1, Street 1, Rawalpindi",
//            "gps_address": "1047, Street 01, Rawalpindi",
//            "location": "0",
//            "sec_mobile": "03445774617",
//            "r_id": "0",
//            "description": "Confim",
//            "accepted_by": "None",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "5",
//            "name": "Umair Sajid Minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "1580982240871",
//            "date_time": "2020-02-06 04:44:02",
//            "total_price": "1125",
//            "status": "5",
//            "address": "House 1, Street 1, Rawalpindi",
//            "gps_address": "1047, Street 01, Rawalpindi",
//            "location": "0",
//            "sec_mobile": "03445774617",
//            "r_id": "29",
//            "description": "Confim",
//            "accepted_by": "None",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        },
//        {
//            "id": "4",
//            "name": "Umair Sajid",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "216542959298456",
//            "date_time": "2020-02-06 04:20:41",
//            "total_price": "450",
//            "status": "7",
//            "address": "House No. 5656,Street gh",
//            "gps_address": "Plot 995, Karim Block Ravi Block Allama Iqbal Town, Lahore, Punjab, Pakistan",
//            "location": "31.5089071,74.2793859",
//            "sec_mobile": "03095927355",
//            "r_id": "1",
//            "description": "Call me before deliver",
//            "accepted_by": "umair.umair1735@gmail.com",
//            "coupen_off": "30",
//            "branch_email": "",
//            "count": "0",
//            "status_name": "Delivered"
//        },
//        {
//            "id": "3",
//            "name": "Umair Sajid",
//            "mobile_number": "03445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "216542959298456",
//            "date_time": "2020-02-06 02:37:35",
//            "total_price": "450",
//            "status": "2",
//            "address": "House No. 5656,Street gh",
//            "gps_address": "Plot 995, Karim Block Ravi Block Allama Iqbal Town, Lahore, Punjab, Pakistan",
//            "location": "31.5089071,74.2793859",
//            "sec_mobile": "03095927355",
//            "r_id": "1",
//            "description": "Call me before deliver",
//            "accepted_by": "umair.umair1735@gmail.com",
//            "coupen_off": "0",
//            "branch_email": "Rewayat@gmail.com",
//            "count": "0",
//            "status_name": "Processing"
//        },
//        {
//            "id": "1",
//            "name": "Umair Sajid minhas",
//            "mobile_number": "+923445774617",
//            "user_email": "umairsajid0017@yahoo.com",
//            "order_number": "22222",
//            "date_time": "2020-01-29 03:51:02",
//            "total_price": "474",
//            "status": "5",
//            "address": "street 2,abc,4",
//            "gps_address": "",
//            "location": "33.1974846,73.2033544",
//            "sec_mobile": "",
//            "r_id": "120",
//            "description": " for biryani lovers, Let's enjoy this.",
//            "accepted_by": "alisyed4107@outlook.com",
//            "coupen_off": "0",
//            "branch_email": "umt@mail.com",
//            "count": "0",
//            "status_name": "Canceled by Restaurant "
//        }
//    ]
//}
